### ISSUE TITLE
SeAct dataset problem about AFE

### ISSUE THREAD

**Issue by hyuqing-zhongmo** [jiazhou-garland/ExACT#10]
Hello，Thank you for your invaluable work.I've met some problems using (AFE)SeAct_dataset.py to divide the SeAct dataset.
Some divided results have different numbers from the paths' numbers provided in SeAct_sampled_train.txt.
For example, m6-yexin-0002 was divided to only one .png file，but there are more paths in the text.

the parameters of the SeAct_dataset.py aren't changed.
self.sample_event_num_min = 100000
self.sample_event_threshold = 40
So what might be the reasons of this problem? Thanks.

**Comment by vlislab22** [comment]
Hello, maybe lower down the self.sample_event_threshold.

**Comment by jiazhou-garland** [comment]
Hello, consider lowering the self.sample_event_threshold and experimenting with different sampling parameters.

**Comment by hyuqing-zhongmo** [comment]
Thanks for your advice!

**Comment by Zizzzzzzz** [comment]
Can you please provide the correct self.sample_event_num_min and self.sample_event_threshold to ensure that consistent results are generated as in SeAct_sampled_train.txt?
