### ISSUE TITLE
PAF dataset problem about classnames_idxs

### ISSUE THREAD

**Issue by linyuming0722** [jiazhou-garland/ExACT#11]
Hello，Thank you for your invaluable work.I've met some problems using train_dp_PAF.py. In the function evaluate_one_epoch,  the values of classnames_idxs seem incorrect. The values of classnames_idxs are as follows:

`classnames_idxs = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
                       1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,
                       1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,
                       2000,2001,2002,2003,2004,2005,2006,
                       3000,3001,3002,3003,3004,3005,3006]
`

but the PAF.json file that records the categories of the PAF dataset only contains 10 classes.

`{"arm crossing": 0, "get up": 1, "jumping": 2, "kicking": 3, "picking up": 4, "sit down": 5, "throwing": 6, "turning around": 7, "walking": 8, "waving": 9}`

Is classnames_idxs correct? If it is incorrect, what is the correct value? 
Looking forward to your reply

**Comment by vlislab22** [comment]
I have rewrite the corresponding part to ensure the classnames_idxs is correct.

**Comment by jiazhou-garland** [comment]
I have rewritten the relevant section to ensure the classnames_idxs is accurate.

**Comment by linyuming0722** [comment]
Thanks a lot for the assistance!
