### ISSUE TITLE
relevant training code

### ISSUE THREAD

**Issue by AirPlanBird** [jiazhou-garland/ExACT#4]
Thank you very much for your contributions in the field of behavior recognition. In your code, I seem to have not found the relevant training code, only the validation-related code. I hope you can provide the relevant part. Wish you smoother progress in your subsequent research endeavors.

**Comment by ssp-seven** [comment]
me too

**Comment by jiazhou-garland** [comment]
Hello, the training codes for HARDVS, SeAct and DVS128Gesture datasets have been released.
