### ISSUE TITLE
AFE

### ISSUE THREAD

**Issue by caomq123** [jiazhou-garland/ExACT#5]
Thank you for your contributions. Could you please explain the relationship between the sample numbering after adaptive sampling and the corresponding sample paths in SeAct_sampled_train.txt? It seems that the number of samples after sampling does not match the number of samples in the txt file. Moreover, why are some of them in even numbers in the txt?

**Comment by jiazhou-garland** [comment]
Hello, the sample number will vary if you change the following two hyperparameters in the init function:

`self.sample_event_num_min = 15000`
`self.sample_event_threshold = 30`

Both parameters are recursive boundary conditions and they are different for different datasets.

**Comment by jiazhou-garland** [comment]
For Q1: 'The number of samples after sampling does not match the number of samples in the txt file.' It is very likely that your choice of the above two parameters is inconsistent with mine.

For Q2: 'why are some of them in even numbers in the txt?', The recursive function will stop when meet boundary conditions, and the final overall data structure of event frames is like a binary tree, and the number of leaf nodes in a binary tree is not necessarily even.
