### ISSUE TITLE
Can't Find "DVS Semantic Action_whole.txt"

### ISSUE THREAD

**Issue by GaoHaokai222** [jiazhou-garland/ExACT#6]
Thank you for your invaluable work. However, I was unable to find the files "DVS Semantic Action_whole.txt" and "DVS Semantic Action.json" in the Dataloader/SeAct folder. Could you kindly check this issue?

Thank you in advance for your help.

**Comment by jiazhou-garland** [comment]
Hello, the whole.txt can be the simple concatenation of the train.txt and val.txt for the DVS Semantic Action dataset. I have uploaded one in the corresponding file, please check it again.

**Comment by GaoHaokai222** [comment]
Sorry for the late reply. I have updated the files. Thanks again for your help and outstanding work.
