### ISSUE TITLE
Question about "Path-to-/DVS128Gesture_sampled_train.txt".

### ISSUE THREAD

**Issue by QiWang233** [jiazhou-garland/ExACT#7]
Hi,

After I transfer event_raw to img(train, val)，I wonder how can I get the "DVS128Gesture_sampled_train.txt".

<img width="269" alt="1727176107453" src="https://github.com/user-attachments/assets/3f9bcf16-76f7-48ad-ba65-794a6fd3e55b">
<img width="521" alt="1727176129998" src="https://github.com/user-attachments/assets/6572ab8a-7f7b-4639-8e8b-e78d4915e782">

**Comment by jiazhou-garland** [comment]
Hello, the sampled dataset.txt contains all paths to your data after the AFE preprocessing.

Please refer to the corresponding files where the examples are provided.
