### ISSUE TITLE
DVS128Gesture训练以及验证精度问题

### ISSUE THREAD

**Issue by alanyz106** [jiazhou-garland/ExACT#9]
你好，我使用了你们给出的DVS128Gesture_sampled_train.txt文件以及对应的验证txt文件，用你们给出的模型checkpoint验证时，发现精度并不是很好，并且我发现你给出的sampled_train.txt文件与实际预处理出来的png文件对应不上，为啥间隔是4或者2呀
![image](https://github.com/user-attachments/assets/40a53ec2-fd59-428f-b2c4-e9a8e961ee10)

**Comment by alanyz106** [comment]
请你能给出对应正确的sampled_train.txt文件吗

**Comment by jiazhou-garland** [comment]
Do you change the config settings when conducting the AFE representation for the DVS128Gesture dataset?
```
 self.sample_event_num_min = 15000
 self.sample_event_threshold = 30
```

**Comment by jiazhou-garland** [comment]
Can you show me the event frame after the AFE representation?

**Comment by jiazhou-garland** [comment]
Due to the variability in the number of resulting event frames, a large number of event frames in a single sequence within a mini-batch can lead to GPU memory overload. Therefore, we sample the resulting event frames to maintain training stability.

**Comment by alanyz106** [comment]
![image](https://github.com/user-attachments/assets/f54823a7-4759-402b-ad79-6192ebd8b3b9)
这是我经过AFE处理过后的DVS128Gesture，其中每个照片都是连续的，而不是你仓库里面的间隔为2或者4

**Comment by vlislab22** [comment]
Yes, so I downsample the preprocessed event frames every 2 or 4 or 8 invertal to ensure the batch size won't be too large.

**Comment by vlislab22** [comment]
看看你最后生成的event frame长什么样子？

**Comment by jiazhou-garland** [comment]
I downsample the preprocessed event frames at intervals of 2,4, or 8 to keep the batch size manageable. What does your final event frame look like?
